### PR TITLE
#4 update README.md for table of contents

### PR DESCRIPTION
**Pull request by navu9999**

### CODE REVIEW

**Comment by garimasingh128** [comment]
The link which I sent you was only for reference. You can change the table of contents and options under it as per the project. Like instead of Goal you can use Vison and reference it to the heading (#-vision). 
(optional) Also if some particular content is missing, you can write it yourself. For ex: we don't have an usage currently, so maybe you can write something for it and it's use cases.

**Comment by navu9999** [comment]
Thank you for the feedback .. I will do the required.

**Comment by garimasingh128** [comment]
Great! Merging it.

**Comment by garimasingh128** [comment]
@all-contributors please add @navu9999  for documentation.

**Pull request merged**
