### PR TITLE
Added more social media icons and corrections

### LINKED ISSUE #18: Adding more social media icons and corrections.
1. Add social media icons for the following:
- Blog website
- Medium
- Bitbucket
2. Correct the color pallette of existing and new icons. For example: For Github use black and white icon instead of the already present green one.

### PR DESCRIPTION
**Pull request by snehaM2210**
# Description

I've added more social media icons like Gmail and Bitbucket and have changed the body size to fit the icons properly. I've changed the color of each icon according to the most appropriate official color code. I've also changed the listing of accounts in edit.html according to the icons listing in popup.html.
Fixes #18  (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I've tested this after each and every change and it's working perfectly well.

- [x] Test A
- [x] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
profile
profileLauncher

### CODE REVIEW

**Comment by snehaM2210** [comment]
Mam, Please review and merge my PR @garimasingh128 .

**Comment by snehaM2210** [comment]
@garimasingh128 Hope you liked the icon changes mam, please merge it😊🤗.

**Comment by garimasingh128** [comment]
Looks good!

**Comment by snehaM2210** [comment]
> Looks good!

Thank you Mam❤️

**Pull request merged**
