### PR TITLE
popup.html file edited as per design

### LINKED ISSUE #38: Make the layout of popup.html as the design
**Is your feature request related to a problem? Please describe.**
Make the layout of popup.html as the design.

**Describe the solution you'd like**
The design folder is present in the root of the master branch. It has all the assets and inspirational designs.

**Describe alternatives you've considered**
You can add your own insights but don't modify it considerably.

**Additional context**
No

### PR DESCRIPTION
**Pull request by PinRathod**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #38 

## Type of change

Please delete options that are not relevant and insert x in the box to check the box.

- popup.html file edited as per design

# How Has This Been Tested?

- Tested the popup file as per design on chrome.

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by PinRathod** [comment]
@garimasingh128 
Please review my PR. Thank you.

**Comment by garimasingh128** [comment]
Conflicting files
HTML_files/popup.html
HTML_files/splash_screen.html

Please resolve these. And don't forget to mention me.

**Comment by PinRathod** [comment]
@garimasingh128 
Check it now. Thank you.

**Comment by garimasingh128** [comment]
Good work!

**Pull request merged**
