### PR TITLE
Changed the colors and added new logos

### PR DESCRIPTION
**Pull request by dijodaiju7**
Changes made:
Added logo of a Blog Website
Added logo of a Bitbucket
Changed the colors of logos to original color scheme

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@dijodaiju7 Use Pull Request Template

**Comment by dijodaiju7** [comment]
Ok

**Comment by Vishal-raj-1** [comment]
@dijodaiju7  You don't need to close this PR. Just edit your PR message like 👍🏻 

fd

READ [pull_request_template.md](https://github.com/garimasingh128/profext/blob/master/pull_request_template.md)

**Comment by dijodaiju7** [comment]
I've created a new pull request and have done accordingly

**Pull request closed without merging**
