### PR TITLE
Update pull_request_template.md

### LINKED ISSUE #67: Add pull request template
Describe the solution you'd like
To ease the work of maintainer, add some checkbox in the PR request template so that a person creates pr after complying with organisations rules.

Additional context
It could look something like this:

 -Have you followed the Contribution guide?
 -Have you made corresponding changes to the documentation?
 -Your submission doesn't break any existing feature.

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
# Description

"How to check the box for the Newbie in PULL REQUEST TEMPLATE"

I am adding this line: `insert x in the box to check the box` so that it will be clearly mentioned how to check the box. This will fixed #67 . @garimasingh128

### CODE REVIEW

**Comment by garimasingh128** [comment]
PR Template is already present. Mention the issue it solves please.

**Comment by Vishal-raj-1** [comment]
> PR Template is already present. Mention the issue it solves please.

I have adding "how to check the box?" for newbie who don't know how mark the task list, it would be better if we 
explicitly mention how to do that.

**Comment by Vishal-raj-1** [comment]
@garimasingh128 If you don't want to merge this minor change you can close this PR !!

**Comment by garimasingh128** [comment]
Merged it but it won't count towards NWOC 2020 points.

**Comment by Vishal-raj-1** [comment]
> Merged it but it won't count towards NWOC 2020 points.

Thanks for merging and No Problem About Points.

Cheers !!

**Pull request merged**
