### PR TITLE
completing Edit and adding social links working 

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes - #15  #9 #10 #11 #7
- [x] Updated popup.html, added edit button further UI improvements will be done.
- [x] create popup.js to retrieve social URLs
- [x] create edit.html, initial UI and working structure of editing URL
- [x] create edit.js

### CODE REVIEW

**Comment by maze-runnar** [comment]
Screenshot from 2020-06-19 17-07-03
Screenshot from 2020-06-19 17-07-16

**Comment by maze-runnar** [comment]
@garimasingh128 please review and merge so that I can enhance it's UI.

**Comment by garimasingh128** [comment]
I'll review it. Just a suggestion for next time: Claim the issue first, get it assigned and then start working on it. :)

**Comment by maze-runnar** [comment]
@garimasingh128 any updates on review?

**Comment by garimasingh128** [comment]
- Please make another PR on develop branch and close this one. 
- You can improve the styling of form and buttons a little bit. Try using neutral colors and smaller widths.
- Instead of giving placeholder text in form, give hardcoded strings like "LinkedIn:" etc. in front of the inputbox.

**Pull request closed without merging**
